### ISSUE TITLE
socket.error: [Errno 128] Transport endpoint is not connected

### ISSUE THREAD

**Issue by myloginid** [jordoncm/youtube-dl-playlist#11]
$ ls /usr/local/bin/you*
/usr/local/bin/youtube-dl  /usr/local/bin/youtube-dl-playlist

$ /usr/local/bin/youtube-dl-playlist PL6gx4Cwl9DGCzVMGCPi1kwvABu7eWv08P /cygdrive/c/documents/Hadoop/
Getting playlist information ...
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl-playlist", line 119, in <module>
    downloader.download(PLAYLIST_ID);
  File "/usr/local/bin/youtube-dl-playlist", line 30, in download
    data = self.fetchInfo(playlistId)
  File "/usr/local/bin/youtube-dl-playlist", line 75, in fetchInfo
    'v' : 2
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 128] Transport endpoint is not connected

**Comment by jordoncm** [comment]
This looks like a network issue. Have you tried running the script again? I am able to hit the URL for this playlist manually and it seems fine.

http://gdata.youtube.com/feeds/api/playlists/PL6gx4Cwl9DGCzVMGCPi1kwvABu7eWv08P/?v=2&alt=json

**Comment by myloginid** [comment]
Hi,

Thanks for the response. I got the issue fixed by using youtube-dl with start and stop playlist videos settings and looped around to download all the videos in batches of 5 in parallel. I will try the playlist download next time and confirm if it still gives an error.

Thanks,
Manish
